# Generated by Django 6.0.3 on 2026-04-05 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("grade", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "indexes": [
                    models.Index(fields=["tenant_id"], name="idx_students_tenant"),
                    models.Index(
                        fields=["grade", "section"], name="idx_students_grade_section"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("embedding", models.JSONField()),
                ("version", models.IntegerField(default=1)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admins.admin",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_embeddings",
                "indexes": [
                    models.Index(
                        fields=["student"], name="idx_student_embeddings_student"
                    ),
                    models.Index(
                        fields=["tenant_id"], name="idx_student_embeddings_tenant"
                    ),
                ],
                "unique_together": {("student", "version")},
            },
        ),
    ]
