# Generated by Django 6.0.3 on 2026-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentembedding_backend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentembedding",
            name="detector",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
