# Generated by Django 6.0.3 on 2026-04-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("grade", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=20)),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes",
                        to="admins.admin",
                    ),
                ),
            ],
            options={
                "db_table": "classes",
                "indexes": [
                    models.Index(fields=["tenant_id"], name="idx_classes_tenant"),
                    models.Index(fields=["teacher"], name="idx_classes_teacher"),
                ],
                "unique_together": {("tenant_id", "grade", "section", "academic_year")},
            },
        ),
    ]
