# Generated by Django 6.0.3 on 2026-05-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={
                ("tenant_id", "grade", "section", "subject", "academic_year")
            },
        ),
    ]
