-- V001__create_admins_table.sql (SQLite)
CREATE TABLE admins (
    id                  TEXT PRIMARY KEY,                          -- UUID generated by app
    tenant_id           TEXT NOT NULL,
    admin_name          TEXT NOT NULL,
    email               TEXT UNIQUE NOT NULL,
    password_hash       TEXT NOT NULL,
    role                TEXT NOT NULL CHECK (role IN ('teacher', 'admin', 'principal')),
    authorization_level INTEGER DEFAULT 1,                         -- 1=teacher, 2=admin, 3=principal
    is_active           INTEGER DEFAULT 1,                         -- 1=true, 0=false
    created_at          TEXT DEFAULT (datetime('now')),
    updated_at          TEXT DEFAULT (datetime('now'))
);

CREATE INDEX idx_admins_tenant ON admins(tenant_id);
CREATE INDEX idx_admins_email ON admins(email);
