-- V002__create_students_table.sql (SQLite)
CREATE TABLE students (
    id              TEXT PRIMARY KEY,                              -- UUID generated by app
    tenant_id       TEXT NOT NULL,
    student_id      TEXT UNIQUE NOT NULL,
    name            TEXT NOT NULL,
    grade           TEXT NOT NULL,
    section         TEXT NOT NULL,
    is_active       INTEGER DEFAULT 1,                             -- 1=true, 0=false
    created_at      TEXT DEFAULT (datetime('now')),
    updated_at      TEXT DEFAULT (datetime('now'))
);

CREATE INDEX idx_students_tenant ON students(tenant_id);
CREATE INDEX idx_students_grade_section ON students(grade, section);
