# Generated by Django 6.0.3 on 2026-07-31 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_auth_hardening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="authorization_level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
