# Generated by Django 6.0.3 on 2026-04-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0001_initial"),
        ("classes", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("date", models.DateField()),
                ("checkin_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("is_manual_override", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="classes.class",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admins.admin",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_attendance",
                "indexes": [
                    models.Index(
                        fields=["student", "date"], name="idx_attendance_student_date"
                    ),
                    models.Index(
                        fields=["tenant_id", "date"], name="idx_attendance_tenant_date"
                    ),
                    models.Index(fields=["class_ref"], name="idx_attendance_class"),
                ],
            },
        ),
    ]
